name: Deploy dev to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set start time
        id: start-time
        run: echo "START_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy changes to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/frontend_dev
            git pull
            docker compose up --force-recreate -d --no-deps --remove-orphans --build frontend_dev

      - name: Set end time
        id: end-time
        run: echo "END_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Calculate duration
        id: duration
        run: |
          START_TIME=$(date -d "${{ env.START_TIME }}" +%s)
          END_TIME=$(date -d "${{ env.END_TIME }}" +%s)
          DURATION=$((END_TIME - START_TIME))
          MINUTES=$((DURATION / 60))
          SECONDS=$((DURATION % 60))
          FORMATTED_DURATION=$(printf "%02d:%02d" $MINUTES $SECONDS)
          echo "DURATION=${FORMATTED_DURATION}" >> $GITHUB_ENV

      - name: Send success message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ @mytemalev успешный деплой на дев:

            ${{ github.event.head_commit.message }}

            Репозиторий: ${{ github.repository }}

            Время начала сборки: ${{ env.START_TIME }}
            Время завершения сборки: ${{ env.END_TIME }}
            Длительность сборки: ${{ env.DURATION }}

            https://dev.parfburo.com

      - name: Send error message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ @mytemalev ошибка деплоя на дев:

            Репозиторий: ${{ github.repository }}

            Время начала сборки: ${{ env.START_TIME }}
            Время завершения сборки: ${{ env.END_TIME }}
            Длительность сборки: ${{ env.DURATION }}

            Посмотреть: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send cancelled message
        if: ${{ cancelled() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ⛔️ @mytemalev деплой на дев отменен:

            Репозиторий: ${{ github.repository }}

            Время начала сборки: ${{ env.START_TIME }}
            Время завершения сборки: ${{ env.END_TIME }}
            Длительность сборки: ${{ env.DURATION }}

            Посмотреть: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
